services:
  - type: web
    name: e-commerce-backend
    env: node
    plan: free
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        value: YOUR_DATABASE_URL
      - key: JWT_SECRET
        value: YOUR_JWT_SECRET
    env: 
      - key: NODE_ENV
        value: production
